server:
  port: 1450

spring:
  application:
    name: liq-msa-bs-bank-transactions
  header:
    channel: digital
    medium: web
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      "classpath:db/migration"
    sql-migration-suffixes:
      ".sql"
    sql-migration-prefix:
      V
    sql-migration-separator:
      "__"
  r2dbc:
    url: r2dbc:pool:mssql://localhost:1433/Prueba
    username: sa
    password: 1234

  datasource:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 1000
      max-lifetime: 1000

